// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ucondo.Infrastructure.Data;

#nullable disable

namespace Ucondo.Infrastructure.Data.Migrations
{
    [DbContext(typeof(UcondoDbContext))]
    [Migration("20250813105950_AddNewFieldCodeSegment")]
    partial class AddNewFieldCodeSegment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Ucondo.Core.AccountAggregate.Account", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowsPostings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeSegment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentCode");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Ucondo.Core.AccountAggregate.Account", b =>
                {
                    b.HasOne("Ucondo.Core.AccountAggregate.Account", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
